apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: memos
  namespace: flux-system
spec:
  path: "./manifests/apps/memos/app"
  postBuild:
    substitute:
      APP_NAME: memos
      APP_NAMESPACE: apps
