apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cloudbeaver
  namespace: flux-system
spec:
  path: "./manifests/apps/cloudbeaver/app"
  postBuild:
    substitute:
      APP_NAME: cloudbeaver
      APP_NAMESPACE: apps
