---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: kube-prometheus-stack-source
  namespace: flux-system
spec:
  interval: 1h
  url: https://github.com/prometheus-community/helm-charts.git
  ref:
    # TODO trace me via renovate
    # renovate: datasource=github-releases depName=prometheus-community/helm-charts
    # What：与 HelmRelease 的 kube-prometheus-stack 版本对齐。
    # Why：避免 CRD 与 chart 版本不匹配导致异常。
    tag: kube-prometheus-stack-80.11.0
  ignore: |
    # exclude all
    /*
    # include deploy crds dir
    !/charts/kube-prometheus-stack/charts/crds/crds
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kube-prometheus-stack-crds
  namespace: flux-system
spec:
  interval: 1h
  prune: true
  sourceRef:
    kind: GitRepository
    name: kube-prometheus-stack-source
  healthChecks:
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: alertmanagerconfigs.monitoring.coreos.com
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: alertmanagers.monitoring.coreos.com
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: podmonitors.monitoring.coreos.com
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: probes.monitoring.coreos.com
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: prometheuses.monitoring.coreos.com
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: prometheusrules.monitoring.coreos.com
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: servicemonitors.monitoring.coreos.com
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: thanosrulers.monitoring.coreos.com
