---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - memos/ks.yaml
  - cloudbeaver/ks.yaml
  - openlist/ks.yaml
  - atuin/ks.yaml
  - n8n/ks.yaml
  - rsshub/ks.yaml
  - beszel/ks.yaml
  - cloudflared/ks.yaml
  - rustdesk/ks.yaml
  - watchtower/ks.yaml
  - wxedge/ks.yaml
