---
#  https://linux.do/t/topic/483523
#  https://linux.do/t/topic/32503/75

#  shufflewzc/faker2：京东脚本库助力池版，提供强大的京东自动化功能。
#  shufflewzc/faker3：京东脚本库内部互助版，适合团队或互助小组使用。
#  6dylan6/jdpro：另一个京东脚本库，与faker形成互补，持续更新，适用于不同需求。
#  leafTheFish/DeathNote：提供多个APP签到类脚本，JS加密保护，安全可靠。
#  smallfawn/QLScriptPublic：包含近百个APP、小程序签到类脚本，部分经过JS加密处理。
#  lzwme/ql-scripts：个人维护的基于需求的自用青龙脚本集，以TypeScript编写，实用性强。

#  https://qinglong.online/en/guide/getting-started/installation-guide/docker-compose
#  https://github.com/Sitoi/dailycheckin
#  https://qd-today.github.io/qd/
#  https://github.com/qd-today/qd
#  https://github.com/einverne/dockerfile/tree/master/qiandao



services:
  web:
    image: whyour/qinglong:latest # 基于 Debian 的版本：whyour/qinglong:debian
    volumes:
      - ./data:/ql/data
    ports:
      - "5700:5700"
    environment:
      QlBaseUrl: '/' # 部署路径非必须，以斜杠开头和结尾，比如 /test/
    restart: unless-stopped
