apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cilium
  namespace: flux-system
spec:
  path: "./manifests/core/networking/cilium/operator"
  dependsOn:
    - name: traefik-crds
    - name: prometheus-crds
    - name: cert-manager
