apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: postgres-operator
  namespace: flux-system
spec:
  path: "./manifests/core/database/postgres/operator"
  # What：移除对 prometheus-crds 的依赖。
  # Why：仅影响监控指标 CRD，postgres-operator 基础功能不依赖它。
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: postgres-config
  namespace: flux-system
spec:
  path: "./manifests/core/database/postgres/config"
  dependsOn:
    - name: postgres-operator
