apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: wxedge
  namespace: flux-system
spec:
  path: "./manifests/apps/wxedge/app"
  postBuild:
    substitute:
      APP_NAME: wxedge
      APP_NAMESPACE: apps
