apiVersion: v1
kind: Secret
metadata:
  name: rsshub-secrets
stringData:
  # 重要：第三方平台密钥为空也可运行，但会导致部分源不可用
  YOUTUBE_KEY: "${SECRET_RSSHUB_YOUTUBE_KEY}"
  YUQUE_TOKEN: "${SECRET_RSSHUB_YUQUE_TOKEN}"
  GITHUB_ACCESS_TOKEN: "${SECRET_RSSHUB_GITHUB_ACCESS_TOKEN}"
  PIXIV_REFRESHTOKEN: "${SECRET_RSSHUB_PIXIV_REFRESHTOKEN}"
  SPOTIFY_CLIENT_ID: "${SECRET_RSSHUB_SPOTIFY_CLIENT_ID}"
  SPOTIFY_CLIENT_SECRET: "${SECRET_RSSHUB_SPOTIFY_CLIENT_SECRET}"
