---
# https://github.com/louislam/uptime-kuma/blob/master/compose.yaml

name: uptime

services:
  uptime-kuma:
    image: louislam/uptime-kuma:2
    restart: unless-stopped
    volumes:
      - /var/lib/uptime/data:/app/data
    ports:
      # <Host Port>:<Container Port>
      - "3001:3001"
