apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: reloader
  namespace: flux-system
spec:
  path: "./manifests/core/system/reloader/app"
  dependsOn:
    - name: prometheus-crds
  postBuild:
    substitute:
      APP_NAME: reloader
      APP_NAMESPACE: system
