apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: reloader
  namespace: flux-system
spec:
  path: "./manifests/core/system/reloader/app"
  # What：移除对 prometheus-crds 的依赖。
  # Why：reloader 不依赖 Prometheus 指标 CRD，可独立启动。
  postBuild:
    substitute:
      APP_NAME: reloader
      APP_NAMESPACE: system
