apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: rsshub
  namespace: flux-system
spec:
  path: "./manifests/apps/rsshub/app"
  postBuild:
    substitute:
      APP_NAME: rsshub
      APP_NAMESPACE: apps
