apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: atuin
  namespace: flux-system
spec:
  path: "./manifests/apps/atuin/app"
  postBuild:
    substitute:
      APP_NAME: atuin
      APP_NAMESPACE: apps
