apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: watchtower
  namespace: flux-system
spec:
  path: "./manifests/apps/watchtower/app"
  postBuild:
    substitute:
      APP_NAME: watchtower
      APP_NAMESPACE: apps
