apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: openlist
  namespace: flux-system
spec:
  path: "./manifests/apps/openlist/app"
  postBuild:
    substitute:
      APP_NAME: openlist
      APP_NAMESPACE: apps
