apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cloudflared
  namespace: flux-system
spec:
  path: "./manifests/apps/cloudflared/app"
  postBuild:
    substitute:
      APP_NAME: cloudflared
      APP_NAMESPACE: apps
