---
#  # https://mynixos.com/nixpkgs/package/rustdesk-server
#  # https://mynixos.com/nixpkgs/options/services.rustdesk-server


#networks:
#  rustdesk-net:
#    external: false
#
#services:
#  hbbs:
#    container_name: hbbs
#    ports:
#      - 21115:21115
#      - <hbbs_port>:21116 # 自定义 hbbs 映射端口
#      - <hbbs_port>:21116/udp # 自定义 hbbs 映射端口
#    image: rustdesk/rustdesk-server
#    command: hbbs
#    volumes:
#      - <mount_path>:/root # 自定义挂载目录
#    networks:
#      - rustdesk-net
#    depends_on:
#      - hbbr
#    restart: unless-stopped
#    deploy:
#      resources:
#        limits:
#          memory: 64M
#
#  hbbr:
#    container_name: hbbr
#    ports:
#      - <hbbr_port>:21117 # 自定义 hbbr 映射端口
#    image: rustdesk/rustdesk-server
#    command: hbbr
#    volumes:
#      - <mount_path>:/root # 自定义挂载目录
#    networks:
#      - rustdesk-net
#    restart: unless-stopped
#    deploy:
#      resources:
#        limits:
#          memory: 64M



services:
  rust_desk_hbbs:
    container_name: rust_desk_hbbs
    image: rustdesk/rustdesk-server
    restart: always
    ports:
      - "21114:21114"
      - "21115:21115"
      - "21116:21116"
      - "21116:21116/udp"
      - "21118:21118"
    command: ["hbbs", "-r", "${HOST}", "-m", "demo"]
    volumes:
      - rust_desk_hbbs_data:/root
    networks:
      - rust_desk_net

  rust_desk_hbbr:
    container_name: rust_desk_hbbr
    image: rustdesk/rustdesk-server
    restart: always
    ports:
      - "21117:21117"
      - "21119:21119"
    command: ["hbbr", "-m", "demo"]
    volumes:
      - rust_desk_hbbr_data:/root
    networks:
      - rust_desk_net

volumes:
  rust_desk_hbbs_data:
    name: rust_desk_hbbs_data
  rust_desk_hbbr_data:
    name: rust_desk_hbbr_data

networks:
  rust_desk_net:
    driver: bridge
