apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: beszel
  namespace: flux-system
spec:
  path: "./manifests/apps/beszel/app"
  postBuild:
    substitute:
      APP_NAME: beszel
      APP_NAMESPACE: apps
