---

#  # https://mynixos.com/nixpkgs/options/services.n8n
#  # https://mynixos.com/nixpkgs/package/n8n
#  # [基于 n8n 的开源自动化：以滴答清单同步 Notion 为例 ｜ 少数派会员 π+Prime](https://sspai.com/prime/story/automation-n8n)
#
