apiVersion: v1
kind: Secret
metadata:
  name: atuin-db
stringData:
  # 数据库用户与库名一般与应用一致，保持只读即可
  ATUIN_DB_USERNAME: "${SECRET_ATUIN_DB_USERNAME}"
  # 重要：数据库密码必须是高强度随机值
  ATUIN_DB_PASSWORD: "${SECRET_ATUIN_DB_PASSWORD}"
  ATUIN_DB_NAME: "${SECRET_ATUIN_DB_NAME}"
